aims = ["Study Python ecosystem for Machine learning: Python, SciPy, Scikit-learn.",
"Study of preprocessing methods. Write a program to find following statistics from a given dataset. Mean, mode, median, variance, standard deviation, quartiles, interquartile range.",
"Study and implement PCA in python.",
"Study and implement simple linear regression.",
"Write a program to demonstrate the working of the decision tree-based ID3 algorithm. Use an appropriate data set for building the decision tree and apply this knowledge to classify a new sample.",
"Write a program to implement the Naïve Bayesian classifier for a sample training data set stored as a .CSV file. Compute the accuracy of the classifier, considering few test data sets.",
"Write a program to implement k-Nearest Neighbour algorithm to classify the iris data set. Compute the accuracy of the classifier, considering few test data sets.",
"Write a program to implement SVM algorithm to classify the iris data set. Compute the accuracy of the classifier, considering few test data sets.",
"Write a program to implement and check Sklearn’s K-Fold, Shuffled K-fold, Repeated K-Fold and Leave-One-Out validation technique for appropriate classification algorithm and dataset.",
"Write a program to implement k-Means clustering algorithm for a sample training data set stored as a .CSV file.",
"Write a program to recognize handwritten digit using Artificial Neural Network.",
"Study Weka toolkit for demonstration of regression, classification and clustering models on it."]
